[project]
name = 'src'
version = '0.0.1'
description = 'Mlops project'
authors = [{name='Rizwan', email = 'mdrizwn12@gmail.com'}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = 'requirements.txt'}